{{- if and .Values.secret.create (not .Values.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-app.secretName" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ required "secret.databaseUsername is required when secret.create=true" .Values.secret.databaseUsername | quote }}
  DB_PWD: {{ required "secret.databasePassword is required when secret.create=true" .Values.secret.databasePassword | quote }}
{{- end }}