---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "java-app.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http